### PR TITLE
fix: pin datafusion versions to 54.0.0 for python subproject

### LINKED ISSUE #2275: python build fails when updated to 54.1
**Describe the bug**

```
   Compiling datafusion-python v54.0.0
error[E0063]: missing field `schema` in initializer of `datafusion::logical_expr::RecursiveQuery`
  --> /Users/marko/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/datafusion-python-54.0.0/src/expr/recursive_query.rs:72:20
   |
72 |             query: RecursiveQuery {
   |                    ^^^^^^^^^^^^^^ missing `schema`

```

**To Reproduce**

```bash
cargo update
cargo test
```

**Expected behavior**

**Additional context**

- datafusion gets updated to 54.1
- looks like the datafusion  54.1 release was not backward compatible release

### PR DESCRIPTION
**Pull request by milenkovicm**
# Which issue does this PR close?

Closes  #2275.

 # Rationale for this change

after 

```
cargo update
```

python CI fails with 

```
   Compiling datafusion-python v54.0.0
error[E0063]: missing field `schema` in initializer of `datafusion::logical_expr::RecursiveQuery`
  --> /Users/marko/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/datafusion-python-54.0.0/src/expr/recursive_query.rs:72:20
   |
72 |             query: RecursiveQuery {
   |                    ^^^^^^^^^^^^^^ missing `schema`
```

It looks like datafusion 54.1.0 is not backward compatible release in this case, so to fix this issue new datafusion-python should be released

# What changes are included in this PR?

- pinned ballista version to `54.0.0`
- pinned datafusion version to `54.0.0`
- pinned datafusion python version to `54.0.0`

# Are there any user-facing changes?

- this is temporary fix to make CI green until we get datafusion-python updated

### CODE REVIEW

**Comment by milenkovicm** [comment]
@andygrove there is issue with python CI, i propose to temporary pin the version used in ballista python to make CI green, we can revert it back once we update to 55 

currently https://github.com/apache/datafusion-ballista/pull/2269 is broken

**Review by avantgardnerio — APPROVED** [review]
In a case of broken-main, I think we should do whatever it takes to get the PRs flowing again.

**Comment by milenkovicm** [comment]
thanks @avantgardnerio for review
