### ISSUE TITLE
python build fails when updated to 54.1

### ISSUE THREAD

**Issue by milenkovicm** [apache/datafusion-ballista#2275]
**Describe the bug**

```
   Compiling datafusion-python v54.0.0
error[E0063]: missing field `schema` in initializer of `datafusion::logical_expr::RecursiveQuery`
  --> /Users/marko/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/datafusion-python-54.0.0/src/expr/recursive_query.rs:72:20
   |
72 |             query: RecursiveQuery {
   |                    ^^^^^^^^^^^^^^ missing `schema`

```

**To Reproduce**

```bash
cargo update
cargo test
```

**Expected behavior**

**Additional context**

- datafusion gets updated to 54.1
- looks like the datafusion  54.1 release was not backward compatible release
